local library = loadstring(game:HttpGet("https://raw.githubusercontent.com/BINjiaobzx6/BINjiao/main/XK%E7%94%A8%E6%88%B7%E7%95%8C%E9%9D%A2.txt"))()
local window = library:new("鹤脚本")

local creds = window:Tab("❤️使用脚本必看♥",'17860099393')

local bin = creds:section("玩家信息",true)

    bin:Label("你的用户名:"..game.Players.LocalPlayer.Character.Name)
    bin:Label("你的注入器:"..identifyexecutor())
    
    local bin = creds:section("关于的脚本和作者的信息",true)
    bin:Label("大群:951177681")
    bin:Label("主作者:鹤，作者QQ3769797457合作Du8")
    bin:Label("副作者：Du8")
    bin:Label("本脚本在俄亥俄州可能不能开启，忍者注入器也不支持开启")
    bin:Label("后续还会添加脚本进来，不会停更，找的一些老外脚本可能不能用见谅")
    bin:Label("欢迎进群让我添加脚本")
    bin:Label("免费模式脚本")
    bin:Label("支持70多个服务器")
    bin:Label("FE所有脚本添加中")
    bin:Label("脚本很好")
    bin:Label("脚本疯狂优化中")
    
local credits = creds:section("关闭",true)

credits:Toggle("脚本框架变小一点", "", false, function(state)
        if state then
        game:GetService("CoreGui")["frosty"].Main.Style = "DropShadow"
        else
            game:GetService("CoreGui")["frosty"].Main.Style = "Custom"
        end
    end)
    credits:Button("关闭脚本",function()
        game:GetService("CoreGui")["frosty"]:Destroy()
    end)
local creds = window:Tab("关于作者",'17860099393')

local credits = creds:section(" 鹤脚本 ",true)
    credits:Button("点我复制作者QQ",function()
    setclipboard("3769797457")
end)
    credits:Button("点我复制群号",function()
    setclipboard("951177681")
end)
    credits:Button("点我复制副作者QQ",function()
    setclipboard("3862221873")
end)

local creds = window:Tab("基本功能",'17860099393')

local credits = creds:section(" 鹤脚本 ",true)

local credits = creds:section("----娱乐----",true)
     credits:Button("非常娱乐",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/KingHaxxor/King-Hax-Gui/main/Arab-Gui%E2%98%85"))();
end)
    credits:Button("聊天气泡美化这个自制",function()
    loadstring(game:HttpGet("https://shz.al/~lniNimeihua"))()
end)
    credits:Button("霖溺FPS",function()
    loadstring(game:HttpGet("https://shz.al/~FHHF"))()
end)
    credits:Button("FPS帧数",function()
     -- Gui to Lua 
 -- Version: 3.2 
  
 -- Instances:
 local ScreenGui = Instance.new("ScreenGui") 
 local FpsLabel = Instance.new("TextLabel")
 
 --Properties:
 
 ScreenGui.Name = "FPSGui" 
 ScreenGui.ResetOnSpawn = false 
 ScreenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling 
 
 FpsLabel.Name = "FPSLabel" 
 FpsLabel.Size = UDim2.new(0, 100, 0, 50) 
 FpsLabel.Position = UDim2.new(0, 10, 0, 10) 
 FpsLabel.BackgroundTransparency = 1 
 FpsLabel.Font = Enum.Font.SourceSansBold 
 FpsLabel.Text = "帧率: 0" 
 FpsLabel.TextSize = 20 
 FpsLabel.TextColor3 = Color3.new(1, 1, 1) 
 FpsLabel.Parent = ScreenGui 
  
 function updateFpsLabel() 
     local fps = math.floor(1 / game:GetService("RunService").RenderStepped:Wait()) 
     FpsLabel.Text = "帧率: " .. fps 
 end 
  
  game:GetService("RunService").RenderStepped:Connect(updateFpsLabel) 
  
 ScreenGui.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")


 animateCredits()
end)
    credits:Button("北京时间",function()
    local LBLG = Instance.new("ScreenGui", getParent)
local LBL = Instance.new("TextLabel", getParent)
local player = game.Players.LocalPlayer

LBLG.Name = "LBLG"
LBLG.Parent = game.CoreGui
LBLG.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
LBLG.Enabled = true
LBL.Name = "LBL"
LBL.Parent = LBLG
LBL.BackgroundColor3 = Color3.new(1, 1, 1)
LBL.BackgroundTransparency = 1
LBL.BorderColor3 = Color3.new(0, 0, 0)
LBL.Position = UDim2.new(0.75,0,0.010,0)
LBL.Size = UDim2.new(0, 133, 0, 30)
LBL.Font = Enum.Font.GothamSemibold
LBL.Text = "TextLabel"
LBL.TextColor3 = Color3.new(1, 1, 1)
LBL.TextScaled = true
LBL.TextSize = 14
LBL.TextWrapped = true
LBL.Visible = true

local FpsLabel = LBL
local Heartbeat = game:GetService("RunService").Heartbeat
local LastIteration, Start
local FrameUpdateTable = { }

local function HeartbeatUpdate()
	LastIteration = tick()
	for Index = #FrameUpdateTable, 1, -1 do
		FrameUpdateTable[Index + 1] = (FrameUpdateTable[Index] >= LastIteration - 1) and FrameUpdateTable[Index] or nil
	end
	FrameUpdateTable[1] = LastIteration
	local CurrentFPS = (tick() - Start >= 1 and #FrameUpdateTable) or (#FrameUpdateTable / (tick() - Start))
	CurrentFPS = CurrentFPS - CurrentFPS % 1
	FpsLabel.Text = ("时间:"..os.date("%H").."时"..os.date("%M").."分"..os.date("%S")).."秒"
end
Start = tick()
Heartbeat:Connect(HeartbeatUpdate)
end)
    credits:Button("玩家加入游戏提示",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/boyscp/scriscriptsc/main/bbn.lua"))()
end)

local credits = creds:section("----通用----",true)
    credits:Button("穿墙",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/TtmScripter/OtherScript/main/Noclip"))()
end)
    credits:Button("操人",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/XmcMKfMV"))()
end)
    credits:Button("人物体积……汉化",function()
    loadstring(game:HttpGet("https://shz.al/~KSJXBC62"))()
end)
    credits:Button("飞行",function()
    loadstring(game:HttpGet("https://shz.al/~hhhh"))()
end)
    credits:Button("夜视仪",function()
    _G.OnShop = trueloadstring(game:HttpGet('https://raw.githubusercontent.com/DeividComSono/Scripts/main/Scanner.lua'))()
end)
    credits:Button("工具包",function()
    loadstring(game:HttpGet("https://cdn.wearedevs.net/scripts/BTools.txt"))()
end)
    credits:Button("反挂机",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/9fFu43FF"))()
end)
    credits:Button("无限跳",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/V5PQy3y0", true))()
end)
    credits:Button("吸人脚本",function()
    loadstring(game:HttpGet("https://shz.al/~HHAKS"))()
end)
    credits:Button("人物无敌",function()
    loadstring(game:HttpGet("https://shz.al/~HHHSNNNKIA"))()
end)
    credits:Button("飞檐走壁",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/zXk4Rq2r"))()
end)
    credits:Button("踏空行走",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/GhostPlayer352/Test4/main/Float'))()
end)
    credits:Button("黑洞脚本",function()
    loadstring(game:HttpGet("https://shz.al/~KAKAKKKKSS"))()
end)
    credits:Button("死亡笔记",function()
    loadstring(game:HttpGet("https://shz.al/~KKKSS"))()
end)
    credits:Button("自杀",function()
    game.Players.LocalPlayer.Character.Humanoid.Health=0
end)
    credits:Button("想杀谁就杀谁",function()
    loadstring(game:HttpGet("https://shz.al/~HHHS"))()
end)
    credits:Button("变玩家",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/XR4sGcgJ"))()
end)
    credits:Button("C00lgui",function()
    loadstring(game:GetObjects("rbxassetid://8127297852")[1].Source)()
end)
    credits:Button("声音播放器",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/GEianeKX"))()
end)
    credits:Button("物理枪",function()
    loadstring(game:HttpGet("https://shz.al/~KJANNKSKKS"))()
end)
    credits:Button("绘制『小天』",function()
    loadstring(game:HttpGet(('https://shz.al/~Xiaotian/ESPScript')))()
end)
    credits:Button("骂人无违规",function()
    loadstring(game:GetObjects("rbxassetid://1262435912")[1].Source)()
end)
    credits:Button("超高画质",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/jHBfJYmS"))()
end)
    credits:Button("工具挂",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Bebo-Mods/BeboScripts/main/StandAwekening.lua"))()
end)
    credits:Button("飞车『霖溺』",function()
    loadstring(game:HttpGet("https://shz.al/~KISJS"))()
end)
    credits:Button("霖溺甩飞",function()
    loadstring(game:HttpGet("https://shz.al/~linNI"))()
end)
    credits:Button("电脑键盘",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/advxzivhsjjdhxhsidifvsh/mobkeyboard/main/main.txt", true))()
end)
    credits:Button("宙斯飞行V3『未汉化』",function()
    loadstring(game:HttpGet("https://shz.al/~ArceusXFlyV3"))()
end)
    credits:Button("霖溺汉化阿尔宙斯飞行『推荐用这个飞行』",function()
    loadstring(game:HttpGet("https://shz.al/~KKDKS"))()
end)
    credits:Button("透视",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Lucasfin000/SpaceHub/main/UESP'))()
end)
local credits = creds:section("----范围----",true)
    credits:Button("正常范围",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/jiNwDbCN"))()
end)
    credits:Button("中等范围",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/x13bwrFb"))()
end)
    credits:Button("高级范围",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/KKY9EpZU"))()
end)

local credits = creds:section("----追踪----",true)
    credits:Button("老外跟踪1『不用自己打字搜索旁边有可以选择玩家』",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Infinity2346/Tect-Menu/main/Teleport%20Gui.lua'))()
end)
    credits:Button("霖溺的跟踪玩家『需要自己搜索，每次跟踪都要点击』",function()
    loadstring(game:HttpGet("https://shz.al/xtQP"))()
end)
    credits:Button("老外跟踪脚本2『需要自己搜索，但是点击后就不用点击了，只不过不能移动，需要变小建议找霖溺』",function()
    loadstring(game:HttpGet("https://shz.al/~LDSLS66"))()
end)
    credits:Button("宙斯自瞄『未汉化』",function()
    loadstring(game:HttpGet("https://shz.al/~ArceusXAimbot"))()
end)
local creds = window:Tab("脚本合集",'17860099393')
    
local credits = creds:section("作者脚本",true)
    credits:Button("林脚本",function()
    lin = "作者林"lin ="林QQ群 747623342"loadstring(game:HttpGet("https://raw.githubusercontent.com/linnblin/lin/main/lin"))()
end)
    credits:Button("禁漫中心",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/dingding123hhh/anlushanjinchangantangwanle/main/jmjmjmjmjmjmjmllllllllllllllllllllllllllllllllIIIIIIIllll.lua"))()
end)
    credits:Button("鸭hub『鸭不更了霖溺来』",function()
    loadstring(game:HttpGet("https://shz.al/~cfde212"))()
end)
    credits:Button("龙脚本",function()
    getgenv().long = "龙脚本，加载时间长请耐心"loadstring("\108\111\97\100\115\116\114\105\110\103\40\103\97\109\101\58\72\116\116\112\71\101\116\40\34\104\116\116\112\115\58\47\47\114\97\119\46\103\105\116\104\117\98\117\115\101\114\99\111\110\116\101\110\116\46\99\111\109\47\108\121\121\97\105\110\105\47\108\111\110\47\109\97\105\110\47\108\105\115\119\109\34\41\41\40\41")()
end)

local credits = creds:section("霖溺电脑端脚本",true)
    credits:Button("霖溺脚本电脑端的",function()
    loadstring(game:HttpGet("https://shz.al/~jxjzj"))()
end)
    credits:Button("霖溺另一个手机端脚本（二改的）",function()
    loadstring(game:HttpGet("https://shz.al/~GHBBJJ"))()
end)
    credits:Button("霖溺超多脚本",function()
    loadstring(game:HttpGet("https://shz.al/~KJANN"))()
end)
local credits = creds:section("作者脚本",true)
    credits:Button("听说最新云脚本",function()
    _G.CloudScript = "云脚本主群号526684389"
loadstring(game:HttpGet("https://raw.githubusercontent.com/XiaoYunCN/LOL/main/%E4%BA%91%E8%84%9A%E6%9C%ACCloud%20script.lua", true))()
end)
    credits:Button("云脚本",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/XiaoYunCN/Xiao-Yun-UWU/main/%E6%B5%B7%E8%B4%BC%E7%8E%8Bbf.lua", true))()
end)
    credits:Button("山脚本",function()
    loadstring(game:HttpGet("https://h.lkmc.asia/script/ssfb.lua"))()
end)
    credits:Button("青脚本",function()
    loadstring(game:HttpGet('https://rentry.co/ct293/raw'))()
end)
    credits:Button("陈脚本",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/QxDD9SpW"))()
end)
    credits:Button("杯脚本",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/zuohongjian/bjb/main/llcq"))()
end)
    credits:Button("北极脚本『中心』",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/KwARpDxV",true))()
end)
    credits:Button("地岩脚本",function()
    loadstring("\108\111\97\100\115\116\114\105\110\103\40\103\97\109\101\58\72\116\116\112\71\101\116\40\34\104\116\116\112\115\58\47\47\114\97\119\46\103\105\116\104\117\98\117\115\101\114\99\111\110\116\101\110\116\46\99\111\109\47\98\98\97\109\120\98\98\97\109\120\98\98\97\109\120\47\99\111\100\101\115\112\97\99\101\115\45\98\108\97\110\107\47\109\97\105\110\47\37\69\55\37\57\57\37\66\68\34\41\41\40\41")()
end)
    credits:Button("导管中心",function()
    loadstring("\108\111\97\100\115\116\114\105\110\103\40\103\97\109\101\58\72\116\116\112\71\101\116\40\34\104\116\116\112\115\58\47\47\114\97\119\46\103\105\116\104\117\98\117\115\101\114\99\111\110\116\101\110\116\46\99\111\109\47\117\115\101\114\97\110\101\119\114\102\102\47\114\111\98\108\111\120\45\47\109\97\105\110\47\37\69\54\37\57\68\37\65\49\37\69\54\37\65\67\37\66\69\37\69\53\37\56\68\37\56\70\37\69\56\37\65\69\37\65\69\34\41\41\40\41\10")()
end)
    credits:Button("脚本中心1.5版本",function()
    loadstring(game:HttpGet("\104\116\116\112\115\58\47\47\112\97\115\116\101\98\105\110\46\99\111\109\47\114\97\119\47\103\101\109\120\72\119\65\49"))()
end)
    credits:Button("玖恶脚本",function()
    loadstring(game:HttpGet('https://ayangwp.cn/api/v3/file/get/8508/%E7%8E%96%E6%81%B6%E4%B8%AD%E5%BF%83.lua?sign=wt54yWf_f0LDB3gXXyQu0SFQ0oUDUXZBOaWQShwCFGg%3D%3A0'))()
end)
    credits:Button("老大脚本",function()
    loadstring(game:HttpGet("https://ayangwp.cn/api/v3/file/get/8401/%E8%80%81%E5%A4%A7%E8%84%9A%E6%9C%AC1.0%E7%89%88.txt?sign=XHxQ1ja8djAnEjVEG-eEZFPeZKFHJ0FHeybHpSbtBW4%3D%3A0"))()
end)
    credits:Button("乌云脚本",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/dT4ZGge8"))()
end)
    credits:Button("皇脚本",function()
    loadstring(game:HttpGet("https://ayangwp.cn/api/v3/file/get/8577/%E7%9A%87v5.txt?sign=ToDT3Udyh4r3WwDu_yVblRL849qC2GJjjjQ7FTidF_w%3D%3A0"))()
end)
    credits:Button("冰红茶脚本",function()
    loadstring(game:HttpGet("https://ayangwp.cn/api/v3/file/get/8582/Protected_9297682332119129.lua?sign=jP-h1AGooC90C0A0O5eDboOCoaQTZpOzLoWzg_oz1eE%3D%3A0"))()
end)
    credits:Button("静新脚本",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/jxdjbx/ggff/main/%E5%B8%85%E9%94%85%E4%B8%80%E6%9E%9A%E5%B0%8F%E5%8F%AF%E7%88%B1%E5%91%80%E5%8F%91%E8%B4%A7%E5%A5%BD%E7%9A%84%E5%90%83%E4%B8%8D%E5%90%83%E8%AE%B0%E5%BE%97%E8%AE%B0%E5%BE%97%E4%BD%A0%E6%96%B9%E4%BE%BF%E6%89%93%E5%BC%80%E7%94%B5%E8%84%91%E6%96%B9%E4%B8%8D%E6%96%B9%E4%BE%BF%E8%AE%B0%E5%BE%97%E9%83%BD%E8%A7%81%E4%B8%8D%E5%88%B0%E6%96%B9%E4%BE%BF%E7%9A%84%E8%AF%9D%E6%89%8B%E6%9C%BA%E6%96%B9%E4%B8%8D%E6%96%B9%E4%BE%BF%E5%B0%B1"))()
end)
    credits:Button("鲨新ui脚本",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fvvhhh/sturdy-octo-engine/main/Protected_1221338743706560.lua.txt"))()
end)
    credits:Button("雷脚本",function()
    loadstring(game:HttpGet(('https://pastebin.com/raw/tPB47inG')))()
end)
    credits:Button("秋脚本",function()
    _G[".秋·自制脚本 遗存抢救"]="2024dncxddtsnchzxtb0112"loadstring(game:HttpGet(utf8.char((function() return table.unpack({104,116,116,112,115,58,47,47,114,97,119,46,103,105,116,104,117,98,117,115,101,114,99,111,110,116,101,110,116,46,99,111,109,47,87,83,98,117,113,47,45,47,109,97,105,110,47,37,69,55,37,65,55,37,56,66,37,67,50,37,66,55,37,69,56,37,56,55,37,65,65,37,69,53,37,56,56,37,66,54,37,69,56,37,56,52,37,57,65,37,69,54,37,57,67,37,65,67})end)())))()
end)
    credits:Button("鱼脚本",function()
    getgenv().FISH = "鱼脚本群:851686462"loadstring("\108\111\97\100\115\116\114\105\110\103\40\103\97\109\101\58\72\101\108\112\71\101\116\40\34\104\116\116\112\115\58\47\47\112\97\115\116\101\98\105\110\46\99\111\109\47\114\97\119\47\72\119\81\77\82\90\68\69\34\41\41\40\41")("鱼脚本")
end)
    credits:Button("火脚本",function()
    loadstring(game:HttpGet("https://shz.al/~FireCatV2RobloxScript"))()
end)

local creds = window:Tab("HUB",'17860099393')

local credits = creds:section("HUB脚本",true)
    credits:Button("EZ-HUB",function()
    loadstring(game:HttpGet(('https://raw.githubusercontent.com/debug42O/Ez-Industries-Launcher-Data/master/Launcher.lua'),true))()
end)
    credits:Button("unfair hub",function()
    loadstring(game:HttpGet(('https://raw.githubusercontent.com/rblxscriptsnet/unfair/main/rblxhub.lua'),true))()
end)
local credits = creds:section("脚本密钥链接https://keyrblx.com/getkey/ShifeScripts",true)
    credits:Button(" Shadow Hub V2",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Alexcirer/Alexcirer/main/V%20d"))()
end)
local credits = creds:section("HUB脚本",true)
    credits:Button("PlaybackX Hub",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/NeaPchX2/Playback-X-HUB/main/Protected.lua.txt'))()
end)
    credits:Button("Tianhe's script hub",function()
    loadstring(game:HttpGet('https://pastebin.com/raw/xdQVhQdm'))()
end)
    credits:Button("Mango hub",function()
    loadstring(game:HttpGet('https://gitlab.com/L1ZOT/mango-hub/-/raw/main/Mango-Bloxf-Fruits-Beta'))()
end)
    credits:Button("SOG hub",function()
    loadstring(game:HttpGet("https://shz.al/~JAJSNN233"))()
end)
    credits:Button("VG hub",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/1201for/V.G-Hub/main/V.Ghub'))()
end)
    credits:Button("Owl-Hub『嘿嘿』",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/CriShoux/OwlHub/master/OwlHub.txt"))()
end)
    credits:Button("HOHO_hub",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/acsu123/HOHO_H/main/Loading_UI'))()
end)

local creds = window:Tab("FE脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("C00lgui",function()
    loadstring(game:GetObjects("rbxassetid://8127297852")[1].Source)()
end)
    credits:Button("1x1x1x1",function()
    loadstring(game:HttpGet(('https://pastebin.com/raw/JipYNCht'),true))()
end)
    credits:Button("Abyssal sword",function()
    loadstring(game:HttpGet("https://shz.al/~KHHG"))()
end)
    credits:Button("FE传送",function()
    mouse = game.Players.LocalPlayer:GetMouse() tool = Instance.new("Tool") tool.RequiresHandle = false tool.Name = "[FE] TELEPORT TOOL" tool.Activated:connect(function() local pos = mouse.Hit+Vector3.new(0,2.5,0) pos = CFrame.new(pos.X,pos.Y,pos.Z) game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = pos end) tool.Parent = game.Players.LocalPlayer.Backpack
end)
    credits:Button("AKV",function()
    loadstring(game:HttpGet("https://shz.al/~KHHGK"))()
end)
    credits:Button("AK47",function()
    loadstring(game:HttpGet("https://shz.al/~KHHGKK"))()
end)
    credits:Button("AbyssEye",function()
    loadstring(game:HttpGet("https://shz.al/~KHJJ"))()
end)
    credits:Button("Animation ID Player",function()
    loadstring(game:HttpGet("https://shz.al/~KHJJK"))()
end)
    credits:Button("Angel wing master",function()
    loadstring(game:HttpGet("https://shz.al/~HHA"))()
end)
    credits:Button("Amythest Sword",function()
    loadstring(game:HttpGet("https://shz.al/~HHAJ"))()
end)
    credits:Button("Amythest Ninja",function()
    loadstring(game:HttpGet("https://shz.al/~HHAJK"))()
end)
    credits:Button("Baldi FE",function()
    loadstring(game:HttpGet("https://shz.al/~KKHHAJK"))()
end)
    credits:Button("Backup",function()
    loadstring(game:HttpGet("https://shz.al/~KKHHAJKKK"))()
end)
    credits:Button("Aureate",function()
    loadstring(game:HttpGet("https://shz.al/~KKHHAJKK"))()
end)
    credits:Button("Anti Furry lol",function()
    loadstring(game:HttpGet("https://shz.al/~KMH"))()
end)
    credits:Button("Bumper Car",function()
    loadstring(game:HttpGet("https://shz.al/~KMHK"))()
end)
    credits:Button("Bizzaro",function()
    loadstring(game:HttpGet("https://shz.al/~KMHKM"))()
end)
    credits:Button("Billie",function()
    loadstring(game:HttpGet("https://shz.al/~KMHKMM"))()
end)
    credits:Button("Big Daddy",function()
    loadstring(game:HttpGet("https://shz.al/~LBN"))()
end)
    credits:Button("Ban Sword",function()
    loadstring(game:HttpGet("https://shz.al/~LBNK"))()
end)
    credits:Button("cadacus",function()
    loadstring(game:HttpGet("https://shz.al/~LBNKj"))()
end)
    credits:Button("Cop",function()
    loadstring(game:HttpGet("https://shz.al/~LBNKjk"))()
end)
    credits:Button("CLOVR",function()
    loadstring(game:HttpGet("https://shz.al/~kansjs"))()
end)
    credits:Button("Chips",function()
    loadstring(game:HttpGet("https://shz.al/~kkkansjs"))()
end)
    credits:Button("Chara",function()
    loadstring(game:HttpGet("https://shz.al/~97373"))()
end)
    credits:Button("Carnage",function()
    loadstring(game:HttpGet("https://shz.al/~k97373"))()
end)
    credits:Button("Pendulum Hub V5",function()
    loadstring(game:HttpGet("https://shz.al/~k97373k"))()
end)
    credits:Button("PUBG Pan",function()
    loadstring(game:HttpGet("https://shz.al/~k97373kK"))()
end)
    credits:Button("SCP-106",function()
    loadstring(game:HttpGet("https://shz.al/~LDS"))()
end)
    credits:Button("KillbotV2",function()
    loadstring(game:HttpGet("https://shz.al/~LDSLS"))()
end)

local creds = window:Tab("力量传奇",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("修改力量",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/jynzl/main/main/Musclas%20Legenos.lua'))()
end)
    credits:Button("击飞（无视力量耐力）",function()
    loadstring(game:GetObjects("rbxassetid://10123407012")[1].Source)()
end)
    credits:Button("力量传奇gui",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Vice1337/free-scripts-for-roblox/main/Muscle-Legends-3623096087"))()
end)

local creds = window:Tab("极速传奇",'17860099393')

local credits = creds:section("自制为云ui",true)
    credits:Button("霖溺自制极速传奇",function()
    loadstring(game:HttpGet("https://shz.al/~lninjj"))()
end)

local creds = window:Tab("忍者传奇",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("霖溺忍者传奇（来源白貓）",function()
    loadstring(game:HttpGet("https://shz.al/~baimaomeilihh"))()
end)
    credits:Button("忍者传奇",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Zyb150933/zyb/main/123'))()
end)
    credits:Button("忍者（老外1）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/zerpqe/script/main/NinjaLegends.lua"))()
end)
    credits:Button("忍者（老外2）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/ThatBlueDevil/Bleus/main/Ninja%20Legends/Source.lua"))()
end)

local creds = window:Tab("监狱人生",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("油管找的管理员脚本",function()
    loadstring(game:HttpGet("https://shz.al/~ggghhhh"))()
end)
    credits:Button("汉化后的moonhub",function()
    loadstring(game:HttpGet("https://shz.al/~MoonHub"))()
end)
local credits = creds:section("Tiger无敌了",true)
    credits:Button("tiger",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/dalloc2/Roblox/main/TigerAdmin.lua"))()
end)
local credits = creds:section("霖溺嘿",true)
    credits:Button("听说吊打一切",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Denverrz/scripts/master/PRISONWARE_v1.3.txt"))()
end)
    credits:Button("请使用青脚本里的管理员脚本（推荐）",function()
    loadstring(game:HttpGet('https://rentry.co/ct293/raw'))()
end)
    credits:Button("剑客脚本（通用）",function()
    jianke_V4 = "作者_初夏"jianke__V4 = "作者QQ1412152634"jianke___V4 = "剑客QQ群347724155"loadstring(game:HttpGet(('https://shz.al/~JianKeV4')))()
end)

local creds = window:Tab("死亡球",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("死亡球（1）",function()
    loadstring(game:HttpGet("https://github.com/Hosvile/InfiniX/releases/latest/download/main.lua",true))()
end)
    credits:Button("死亡球（2）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/LOLking123456/Ball1/main/Death"))()
end)

local creds = window:Tab("自然灾害",'17860099393')

local credits = creds:section("自制为云ui",true)
    credits:Button("霖溺自制自然灾害",function()
    loadstring(game:HttpGet("https://shz.al/D8Kn"))()
end)
    credits:Button("自然灾害1",function()
    loadstring(game:HttpGet("https://gist.githubusercontent.com/TurkOyuncu99/7c75386107937fa006304efd24543ad4/raw/8d759dfcd95d39949c692735cfdf62baec0bf835/cafwetweg", true))()
end)
    credits:Button("自然灾害2",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/2dgeneralspam1/scripts-and-stuff/master/scripts/LoadstringUjHI6RQpz2o8", true))()
end)
    credits:Button("自然灾害3",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/9NLK7/93qjoadnlaknwldk/main/main'))()
end)

local creds = window:Tab("杀手于警长",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("杀手于警长（找的）",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/yadbPQUm",true))()
end)
    credits:Button("剑客脚本（通用）",function()
    jianke_V4 = "作者_初夏"jianke__V4 = "作者QQ1412152634"jianke___V4 = "剑客QQ群347724155"loadstring(game:HttpGet(('https://shz.al/~JianKeV4')))()
end)

local creds = window:Tab("巴掌模拟器",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("自动刷巴掌",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/ionlyusegithubformcmods/1-Line-Scripts/main/Slap%20Farm'))()
end)
    credits:Button("巴掌模拟器yyds",function()
    loadstring(game:HttpGet("https://shz.al/~HHAKKSSKSOOS"))()
end)
    credits:Button("巴掌模拟器",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/dizyhvh/slap_battles_gui/main/0.lua"))()
end)
    credits:Button("常用功能",function()
    loadstring(game:HttpGet("https://lkhub.net/s/loader.lua"))()
end)
    credits:Button("多功能（老外）",function()
    loadstring(game:HttpGet(("https://raw.githubusercontent.com/ionlyusegithubformcmods/1-Line-Scripts/main/Slap%20Battles")))()
end)

local creds = window:Tab("内脏与黑火药脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("内脏与黑火药",function()
    loadstring(game:HttpGet("https://shz.al/~KSKKS"))()
end)

local creds = window:Tab("51区脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("51区",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/GamingScripter/Saktk-In-Area51/main/Area51", true))()
end)

local creds = window:Tab("短信模拟器脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("短信模拟器",function()
    loadstring(game:HttpGet(('https://pastebin.com/raw/9hxkxUZ5'),true))()
end)

local creds = window:Tab("克隆大亨脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("克隆大亨",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/HELLLO1073/RobloxStuff/main/CT-Destroyer"))()
end)

local creds = window:Tab("刀刃球",'17860099393')

local credits = creds:section("鹤脚本（听说的战场）",true)
    credits:Button("霖溺汉化刀刃球",function()
    loadstring(game:HttpGet("https://shz.al/75G8"))()
end)
    credits:Button("Seeds-Next刀刃球不会的自己研究『强，作者推荐』",function()
    loadstring(game:HttpGet(('https://shz.al/~Seeds-Next/Ditto-so-tried/HAGOU-and-Qumuuuuu')))()
end)
    credits:Button("刀刃球（强1）",function()
    loadstring(game:HttpGet(('https://raw.githubusercontent.com/Unknownkellymc1/Unknownscripts/main/slap-battles')))()
end)
    credits:Button("刀刃球（强2）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/HKLua/Balls/main/DawnLoader.lua"))()
end)
    credits:Button("刀刃球（强3）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/REDzHUB/BladeBall/main/redz9999"))()
end)
    credits:Button("刀刃球（强4）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Neoncat765/Neon.C-Hub-X/main/UnknownVersion"))()
end)
    credits:Button("刀刃球（强5）",function()
    local a,b,c,d=loadstring,request or http_request or (http and http.request) or (syn and syn.request),assert,"https://shz.al/~NeoV4"c(a and b, "Your Executor does not support.")a(b({Url=d,Method="GET"}).Body)()
end)
    credits:Button("刀刃球（强6）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/HKLua/Balls/main/DawnLoader.lua"))()
end)

local creds = window:Tab("模仿者",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("模仿者（1有自动赢）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/ttjy9808/obfloadstringmainmimic/main/README.md", true))()
end)
    credits:Button("模仿者（名字相同脚本不同）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/ttjy9808/obfloadstringmainmimic/main/README.md", true))()
end)

local creds = window:Tab("出租车司机脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("自动抽蛋开启",function()
    loadstring(game:HttpGet("https://shz.al/~KAKSKSK"))()
end)
    credits:Button("自动抽蛋关闭",function()
    loadstring(game:HttpGet("https://shz.al/~KA28272"))()
end)

local creds = window:Tab("战斗勇士",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("战斗勇士（英文电脑端，直接畅玩）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/frkfx/Combat-Warriors/main/Script"))()
end)
    credits:Button("战斗勇士老外英文",function()
    loadstring(game:HttpGet("https://paste.gg/p/anonymous/697fc3cad5f743508318cb7399e89432/files/b5923e52edab4e5c91e46b74563d0ae8/raw"))()
end)
    credits:Button("战斗勇士无限体力",function()
    loadstring(game:HttpGet("https://shz.al/~KSK"))()
end)

local creds = window:Tab("火箭发射模拟器",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("火箭发射模拟器（名字相同脚本不同）",function()
    loadstring(game:HttpGet("https://ayangwp.cn/api/v3/file/get/9245/%E7%8C%AB%E9%80%9A%E7%94%A8.txt?sign=hrWROZdVfK2mtJcIFa3Tvbl-TojP1C86_Zd3q03qttc%3D%3A0"))()
end)
    credits:Button("火箭发射模拟器（名字相同脚本不同）",function()
    loadstring(game:HttpGet(('https://raw.githubusercontent.com/dizyhvh/rbx_scripts/main/321_blast_off_simulator')))()
end)

local creds = window:Tab("只因剑",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("只因剑（名字相同脚本不同）",function()
    loadstring(game:HttpGet(('https://gist.githubusercontent.com/blox-hub-roblox/021bad62bbc6a0adc4ba4e625f9ad7df/raw/c89af6e1acf587d09e4ce4bc7510e7100e0c0065/swordWarrior.lua'),true))()
end)
    credits:Button("只因剑（2召唤小黑子）",function()
    loadstring(game:HttpGet(('https://gist.githubusercontent.com/blox-hub-roblox/021bad62bbc6a0adc4ba4e625f9ad7df/raw/c89af6e1acf587d09e4ce4bc7510e7100e0c0065/swordWarrior.lua'),true))()
end)
    credits:Button("只因剑（3巨剑战士）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/ToraIsMe/ToraIsMe/main/0SwordWarriors"))()
end)

local creds = window:Tab("战争大亨脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("战争大亨",function()
    loadstring(game:HttpGet'https://raw.githubusercontent.com/Macintosh1983/ChillHubMain/main/ChillHubOilWarfareTycoon.lua')()
end)
    credits:Button("狼脚本",function()
    loadstring(game:HttpGet("https://shz.al/~WarTycoon"))()
end)

local creds = window:Tab("彩虹朋友",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("彩虹朋友（名字相同脚本不同）",function()
    loadstring(game:HttpGet("https://pastefy.app/XoNv04vR/raw"))()
end)
    credits:Button("彩虹朋友自动获胜",function()
    loadstring(game:HttpGet("https://shz.al/~zkzkzisKAKAKKKKSS"))()
end)
    credits:Button("彩虹朋友（推荐）",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Ihaveash0rtnamefordiscord/BorkWare/main/Scripts/' .. game.GameId .. ".lua"))(' Watermelon ? ')
end)

local creds = window:Tab("河北唐县",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("河北唐县-2",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Sw1ndlerScripts/RobloxScripts/main/Tang%20Country.lua"))()
end)
    credits:Button("河北唐县-1",function()
    loadstring(game:HttpGet("https://pastefy.app/s20nni0h/raw"))()
end)
    credits:Button("河北唐县1",function()
    loadstring(game:HttpGet("https://pastefy.app/s20nni0h/raw"))()
end)
    credits:Button("河北唐县2",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Sw1ndlerScripts/RobloxScripts/main/Tang%20Country.lua"))()
end)
    credits:Button("河北唐县3",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Marco8642/science/ok/T%20ang%20County"))()
end)

local creds = window:Tab("Blox Fruit",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("霖溺BF",function()
    loadstring(game:HttpGet("https://shz.al/~KAKKKS"))()
end)
    credits:Button("BF『HOHO脚本』链接不一样",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/acsu123/HohoV2/Free/BloxFruitFreeV3.lua"))()
end)
    credits:Button("BF『HOHIO脚本』链接不一样",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/acsu123/HOHO_H/main/Loading_UI'))()
end)
    credits:Button("BF（听说第二强）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Augustzyzx/UraniumMobile/main/UraniumKak.lua"))()
end)
    credits:Button("BF（霖溺找的）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RobloxScriptsExploit/Blox-Fruits/main/Ripper%20M"))()
end)
    credits:Button("BF（自动箱子）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/IceMael7/NewIceHub/main/Brookhaven"))()
end)
    credits:Button("BF（汉化）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/XiaoYunCN/Xiao-Yun-UWU/main/%E6%B5%B7%E8%B4%BC%E7%8E%8Bbf.lua", true))()
end)
    credits:Button("BF（听说最屌）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/AkiraNus/UniquehubKak/main/FreeCr.Xenonhub"))()
end)
    credits:Button("BF（刷怪）",function()
    loadstring(game:HttpGet('https://rawscripts.net/raw/UPDATE-16-Blox-Fruits-Nub-V1-Hub-4583'))()
end)
    credits:Button("BF脚本w-azure无密钥",function()
    getgenv().Team = "Pirates"loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/3b2169cf53bc6104dabe8e19562e5cc2.lua"))()
end)
    credits:Button("BF（自动升级）",function()
    loadstring(game:HttpGet"https://raw.githubusercontent.com/xDepressionx/Free-Script/main/AllScript.lua")()
end)
    credits:Button("BF",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/REDzHUB/BloxFruits/main/redz9999"))()
end)

local creds = window:Tab("进击的僵尸脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("进击的僵尸",function()
    loadstring(game:HttpGet("https://shz.al/~KSKSKSK"))()
end)

local creds = window:Tab("破坏者谜团2",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("破坏者谜团2（多功能）",function()
    loadstring(game:HttpGet(("https://raw.githubusercontent.com/Ethanoj1/EclipseMM2/master/Script"),true))()
end)
    credits:Button("霖溺非常推荐（破坏者谜团2）",function()
    loadstring(game:HttpGet("https://shz.al/~GHD"))()
end)
    credits:Button("破坏者谜团2（老外的）",function()
    loadstring(game:HttpGet("https://shz.al/~GHDJJ"))()
end)
    credits:Button("破坏者谜团2",function()
    loadstring(game:GetObjects("rbxassetid://4001118261")[1].Source)()
end)
    credits:Button("破坏者谜团（透视谁是警长）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Ihaveash0rtnamefordiscord/Releases/main/MurderMystery2HighlightESP"))(' Watermelon ?')
end)

local creds = window:Tab("nico下一个机器人脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("nico下一个机器人",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/elonof/nicosbots-script/main/main.lua",true))()
end)
    credits:Button("nico下一个机器人",function()
    loadstring(game:HttpGet("https://fern.wtf/scripts/nico_bot.lua", true))()
end)
    credits:Button("nico下一个机器人",function()
    local hrp = game.Players.LocalPlayer.Character:FindFirstChild("Humanoid")
hrp.Parent = nil
hrp:Clone()
hrp.Parent = game.Players.LocalPlayer.Character
hrp.Name = "Humanoid"
game.StarterGui:SetCore("SendNotification", {Title="God Mode"; Text="God Mode Activated"; Duration=5;})
end)
    credits:Button("nico下一个机器人",function()
    loadstring(game:HttpGetAsync("https://raw.githubusercontent.com/fartbutt69/Nico-s-Nextbot-Killer/main/script.lua", true))()
end)
    credits:Button("nico下一个机器人",function()
    local Player = game:GetService("Players").LocalPlayer

while true do 
wait(0.5)
Player.Character.HumanoidRootPart.Position = Vector3.new(0, -50, 0)
wait(0.5)
Player.Character.HumanoidRootPart.Position = Vector3.new(0, -80, 0)
end
end)

local creds = window:Tab("犯罪",'17860099393')
    credits:Button("犯罪",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/GlobeReverse/Moonlight/main/Criminality.lua"))()
end)

local creds = window:Tab("蜂群模拟器",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("霖溺简易汉化",function()
    loadstring(game:HttpGet("https://shz.al/~HHAKKJA"))()
end)
    credits:Button("蜂群模拟器",function()
    loadstring(game:HttpGet("https://shz.al/~HHAKKSS"))()
end)
    credits:Button("蜂群模拟器（名字相同脚本不同）",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/3A61hnGA", true))()
end)
    credits:Button("蜂群模拟器bee swarm",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Historia00012/HISTORIAHUB/main/BSS%20FREE"))()
end)
    credits:Button("蜂群模拟器（名字相同脚本不同）",function()
    loadstring(game:HttpGet("https://pastefy.app/QtYmKaQ1/raw"))()
end)
    credits:Button("蜂群模拟器（自动收集）",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/max0mind/lua/main/loader.lua'))()
end)

local creds = window:Tab("小偷模拟器脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("小偷模拟器",function()
    loadstring(game:HttpGet(("https://raw.githubusercontent.com/adrician/Thief-Simulator---GUI/main/Thief%20sim.lua"),true))()
end)

local creds = window:Tab("evade大逃脱",'17860099393')

local credits = creds:section("evade脚本",true)
    credits:Button("evade脚本1",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PepesGH1/stuff/main/evadeloader.lua"))()
end)
    credits:Button("evade大逃脱",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/XiaoYunCN/UWU/main/%E4%BA%91%E8%84%9A%E6%9C%ACEvade.lua"))()
end)
    credits:Button("老外脚本",function()
    loadstring(game:HttpGet("https://shz.al/~jdjsjsKK"))()
end)

local creds = window:Tab("国王遗产脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("『1』",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/sannin9000/scripts/main/kinglegacy.lua"))()
end)
    credits:Button("『2』",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/1f0yt/community/master/legacy"))()
end)
    credits:Button("『3』",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/hajibeza/RIPPER-HUB/main/King%20Leagacy"))()
end)
    credits:Button("『4』",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Strikehubv2z/StormSKz/main/All_in_one"))()
end)

local creds = window:Tab("披萨店脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("披萨点自动工作",function()
    loadstring(game:HttpGet("https://shz.al/~HHHSUSU"))()
end)

local creds = window:Tab("一路向西",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("一路向西（无后坐力超级射速无限子弹）",function()
    loadstring(game:GetObjects("rbxassetid://10040701935")[1].Source)()
end)
    credits:Button("一路向西（名字相同脚本不同）",function()
    loadstring(game:HttpGet(("https://raw.githubusercontent.com/Drifter0507/scripts/main/westbound"),true))()
end)
    credits:Button("一路向西（名字相同脚本不同）",function()
    loadstring(game:HttpGet("https://pastefy.app/q08owYGG/raw"))()
end)

local creds = window:Tab("造船寻宝",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("造船寻宝（名字相同脚本不同）",function()
    loadstring(game:HttpGet("http://dirtgui.xyz/BuildABoat.lua",true))()
end)
    credits:Button("造船寻宝（名字相同脚本不同）",function()
    loadstring(game:HttpGet("https://pastefy.app/hvV1c4nO/raw"))()
end)
    credits:Button("造船寻宝（复制别人船）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/max2007killer/auto-build-not-limit/main/autobuild.txt"))()
end)
    credits:Button("造船寻宝（刷钱）",function()
    loadstring(game:HttpGet(('https://raw.githubusercontent.com/urmomjklol69/GoldFarmBabft/main/GoldFarm.lua'),true))()
end)

local creds = window:Tab("鲨口求生脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("鲨口求生有一些功能慎用",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/YYVLbzVg", true))()
end)

local creds = window:Tab("DOORS",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("小玄奘doors",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/XSKMS/MS-Chinese-XXZ/refs/heads/main/rename.txt"))()
end)
    credits:Button("多功能DOORS",function()
    loadstring(game:HttpGet("https://shz.al/~SJZJJSISI"))()
end)
    credits:Button("DOORS-2",function()
    loadstring(game:HttpGet("https://github.com/DocYogurt/Main/raw/main/Scripts/DF2RW.lua"))()
end)
    credits:Button("Doors汉化hub",function()
    loadstring(game:HttpGet("\104\116\116\112\115\58\47\47\112\97\115\116\101\98\105\110\46\99\111\109\47\114\97\119\47\54\53\84\119\84\56\106\97"))()
end)
    credits:Button("Doors（最强）",function()
    loadstring(game:HttpGet(('https://pastebin.com/raw/R8QMbhzv')))()
end)
    credits:Button("Doors（最强2）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/GamingScripter/Darkrai-X/main/Games/Doors"))()
end)
    credits:Button("1-2通用doors",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Yumiara/Python/main/Main.lua"))();
end)

local creds = window:Tab("破坏模拟器脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("破坏模拟器",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/AquaModz/DestructionSIMModded/main/DestructionSimAqua.lua'))()
end)

local creds = window:Tab("驾驶帝国",'17860099393')

local credits = creds:section("驾驶帝国脚本",true)
    credits:Button("驾驶帝国（英文）",function()
    loadstring(game:HttpGet(('https://raw.githubusercontent.com/zeuise0002/SSSWWW222/main/README.md'),true))()
end)
    credits:Button("驾驶帝国（英文）",function()
    loadstring(game:HttpGet("https://soggyhubv2.vercel.app"))()
end)

local creds = window:Tab("动物进化脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("动物进化1",function()
    game:GetService("ReplicatedStorage").Events.UpdateStatEvent:FireServer("Lv", 999999999)
end)
    credits:Button("动物进化2",function()
    game:GetService("ReplicatedStorage").Events.UpdateStatEvent:FireServer("Xp", 999999999)
end)
    credits:Button("动物进化3",function()
    game:GetService("ReplicatedStorage").Events.UpdateStatEvent:FireServer("DmgLvl", 999999999)
end)
    credits:Button("动物进化4",function()
    game:GetService("ReplicatedStorage").Events.UpdateStatEvent:FireServer("CritDmgLvl", 999999999)
end)
    credits:Button("动物进化",function()
    local player = game.Players.LocalPlayer

for _, child in ipairs(player:GetChildren()) do
    if child:IsA("BoolValue") then
        child.Value = true
    end
end
end)

local creds = window:Tab("最强战场",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("最强战场多功能",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Nicuse/RobloxScripts/main/SaitamaBattlegrounds.lua"))()
end)
    credits:Button("最强战场动作",function()
    loadstring(game:HttpGet("https://rawscripts.net/raw/The-Strongest-Battlegrounds-hub-fr-18520"))()
end)
    credits:Button("最强战场动作2",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/skibiditoiletfan2007/BaldyToSorcerer/main/Latest.lua"))()
end)

local creds = window:Tab("浴缸战争脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("（升级演习）浴缸战争",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Alan0947383/Boom/main/Protected_1198219713372149.lua.txt",true))()
end)
    credits:Button("点我复制解密钥链接",function()
    setclipboard("https://pandadevelopment.net/startkey.html?service=demonichubv2")
end)

local creds = window:Tab("飞行比赛脚本",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("飞行比赛",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/NightCoded/script/main/fly-race.lua"))()
end)

local creds = window:Tab("俄亥俄州",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("俄亥俄州（老外1）",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/0MqfXpvY", true))()
end)
    credits:Button("俄亥俄州（老外2）",function()
    loadstring(game:HttpGet('https://pastebin.com/raw/MyfCUnGK'))()
end)
    credits:Button("bs自动印钞机",function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Asddffgujhh/-/refs/heads/main/Bs%E8%87%AA%E5%8A%A8%E5%8D%B0%E9%92%9E%E6%9C%BA'))()
end)
    credits:Button("俄亥俄州（自动工作＋传送工作地点）",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/LOLking123456/ohio/main/Roblox232"))()
end)
    credits:Button("俄亥俄州1",function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/rxn-xyz/Ohio./main/Ohio.lua",true))()
end)
    credits:Button("俄亥俄州2",function()
    loadstring(game:HttpGet("https://pastefy.app/QbXPfsgC/raw"))()
end)

local creds = window:Tab("压力",'17860099393')

local credits = creds:section("鹤脚本",true)
    credits:Button("万圣节压力",function()
    loadstring(game:HttpGet("\104\116\116\112\115\58\47\47\114\97\119\46\103\105\116\104\117\98\117\115\101\114\99\111\110\116\101\110\116\46\99\111\109\47\67\104\105\110\97\81\89\47\83\99\114\105\112\116\115\47\77\97\105\110\47\80\114\101\115\115\117\114\101"))()
end)
    credits:Button("压力1",function()
    loadstring(game:HttpGet("https://github.com/Drop56796/CreepyEyeHub/blob/main/obfuscate.lua?raw=true"))()
end)
    credits:Button("压力2",function()
    loadstring(game:HttpGet("https://pastebin.com/raw/iZuasZCc"))()
end)